export { default as PathGeneratorInterface } from '~/services/PathGenerator/PathGeneratorInterface'
export { default as CategoryRepositoryInterface } from '~/repositories/Category/CategoryRepositoryInterface'
export { default as PostRepositoryInterface } from '~/repositories/Post/PostRepositoryInterface'
export { default as UserRepositoryInterface } from '~/repositories/User/UserRepositoryInterface'
export { default as ObservableInterface } from '~/events/core/ObservableInterface'
